### ISSUE TITLE
How to use the method on own model

### ISSUE THREAD

**Issue by Zeudfish** [wukailu/MemSR#1]
MemSR is the most impressive paper I have seen recently. However, when I tried to reproduce it, I encountered some problems and would like your advice.

Although your code is based on the EDSR network, I think this should be a method that can be applied to the distillation of various residual tasks. I would like to ask how I should apply MemSR to my model framework. I am not sure if I need to refactor my model, and if so, where in the code should I replace it. I'm sorry that my code level is not as high as yours. Although you have disclosed your code, I still encounter difficulties when I want to freely strip off your method.Looking forward to your reply.

**Comment by wukailu** [comment]
Theoretically this method supports the simplification of all networks consisting of convolutional and residual connections. Code-wise, just refer to MemSR/frameworks/distillation
/MemSR.py to build your model using ConvertibleLayer within model.layerwise_model (i.e. ConvLayer, IdLayer, ConcatLayer), and you can use the existing code to simplify and distill directly. It is worth noting that this method works well for model under 40 layers, too many layers can lead to errors accumulating during the initialization calculation, resulting in poorer results. We have tested that it works poorly on models with 135 layers.
